---
title: "Pspline: Penalized Spline Regression"
output: rmarkdown::github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Pspline

<!-- badges: start -->
<!-- badges: end -->

The goal of Pspline is to fit a regression spline estimator based on penalized B-spline and to visualize its plot.

## Installation

You can install the development version of Pspline like so:

``` r
devtools::install('C:/Users/user/OneDrive/문서/Rproj/Pspline')
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(Pspline)
library(Pspline)

n= 100
x_values= sort(runif(n, 0, 1))
y_values= sin(2*pi*x_values) + cos(4*pi*x_values) + rnorm(n, sd= 0.2)

# spline degree specification
degree= 3

# knot generation
num_interior= 5
interior_knots= knots_quantile(x_values, num_interior)

# setting the value of lambda and the difference penalty order
lambda= 1e-2
diff_order= 2

# model fitting
model= fit_pspline(x_values, y_values, interior_knots, degree, lambda, diff_order)

grid_x= seq(min(x_values), max(x_values), length.out= 100)
plot_pspline(x_values, y_values, model, grid_x)
```
